### ISSUE TITLE
Using the package for overall analysis

### ISSUE THREAD

**Issue by sealx017** [mbernste/SpatialCorr#9]
Hi,

Is it possible to use the package without the tissue region breakdown, i.e., when no cell clustering or annotation information is available?

Thank you.

**Comment by mbernste** [comment]
Hi, 

It should be! If you set `cond_key` to None, then it should just run on the entire slide: https://spatialcorr.readthedocs.io/en/latest/api.html#spatialcorr.run_test

Best,
Matt

**Comment by sealx017** [comment]
Perfect, thank you so much!
